// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonetarisApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonetarisApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127084110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("ai_analysis");

                    b.Property<string>("CompetentCourt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competent_court");

                    b.Property<decimal>("Costs")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("costs");

                    b.Property<string>("CourtFileNumber")
                        .HasColumnType("text")
                        .HasColumnName("court_file_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("DebtorId")
                        .HasColumnType("uuid")
                        .HasColumnName("debtor_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal>("Interest")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("interest");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_action_date");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("principal_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_cases_agent_id");

                    b.HasIndex("DebtorId")
                        .HasDatabaseName("ix_cases_debtor_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_cases_due_date");

                    b.HasIndex("InvoiceNumber")
                        .HasDatabaseName("ix_cases_invoice_number");

                    b.HasIndex("NextActionDate")
                        .HasDatabaseName("ix_cases_next_action_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cases_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cases_tenant_id");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.CaseHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_history");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_history_case_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_case_history_created_at");

                    b.ToTable("case_history", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Debtor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AddressLastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("address_last_checked");

                    b.Property<string>("AddressStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_status");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("boolean")
                        .HasColumnName("is_company");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OpenCases")
                        .HasColumnType("integer")
                        .HasColumnName("open_cases");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RiskScore")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_score");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalDebt")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_debt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_debtors");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_debtors_agent_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_debtors_email");

                    b.HasIndex("RiskScore")
                        .HasDatabaseName("ix_debtors_risk_score");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_debtors_tenant_id");

                    b.ToTable("debtors", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DebtorId")
                        .HasColumnType("uuid")
                        .HasColumnName("debtor_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("DebtorId")
                        .HasDatabaseName("ix_documents_debtor_id");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_documents_uploaded_at");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inquiries");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_inquiries_case_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_inquiries_created_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inquiries_status");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_templates_category");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_templates_tenant_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_templates_type");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountIBAN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_account_iban");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("ContactEmail")
                        .HasDatabaseName("ix_tenants_contact_email");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_registration_number");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarInitials")
                        .HasColumnType("text")
                        .HasColumnName("avatar_initials");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.UserTenantAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "TenantId")
                        .HasName("pk_user_tenant_assignments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_tenant_assignments_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_tenant_assignments_user_id");

                    b.ToTable("user_tenant_assignments", (string)null);
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Case", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cases_users_agent_id");

                    b.HasOne("Monetaris.Shared.Models.Entities.Debtor", "Debtor")
                        .WithMany("Cases")
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cases_debtors_debtor_id");

                    b.HasOne("Monetaris.Shared.Models.Entities.Tenant", "Tenant")
                        .WithMany("Cases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cases_tenants_tenant_id");

                    b.Navigation("Agent");

                    b.Navigation("Debtor");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.CaseHistory", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.Case", "Case")
                        .WithMany("History")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_history_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Debtor", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_debtors_users_agent_id");

                    b.HasOne("Monetaris.Shared.Models.Entities.Tenant", "Tenant")
                        .WithMany("Debtors")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_debtors_tenants_tenant_id");

                    b.Navigation("Agent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Document", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.Debtor", "Debtor")
                        .WithMany("Documents")
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_debtors_debtor_id");

                    b.Navigation("Debtor");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Inquiry", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.Case", "Case")
                        .WithMany("Inquiries")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inquiries_cases_case_id");

                    b.HasOne("Monetaris.Shared.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inquiries_users_created_by");

                    b.Navigation("Case");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Template", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_templates_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.User", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.UserTenantAssignment", b =>
                {
                    b.HasOne("Monetaris.Shared.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenant_assignments_tenants_tenant_id");

                    b.HasOne("Monetaris.Shared.Models.Entities.User", "User")
                        .WithMany("TenantAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenant_assignments_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Case", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Inquiries");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Debtor", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.Tenant", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Debtors");
                });

            modelBuilder.Entity("Monetaris.Shared.Models.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("TenantAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
